// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Conditions struct {
	Slug   *string `json:"Slug,omitempty"`
	UserID *string `json:"UserId,omitempty"`
}

type CreatePost struct {
	Slug     string  `json:"Slug"`
	Title    string  `json:"Title"`
	Content  string  `json:"Content"`
	ImageURL *string `json:"ImageUrl,omitempty"`
}

type Post struct {
	ID        int    `json:"ID"`
	Slug      string `json:"Slug"`
	Title     string `json:"Title"`
	UserID    int    `json:"UserID"`
	Content   string `json:"Content"`
	ImageURL  string `json:"ImageURL"`
	Status    string `json:"Status"`
	Views     int    `json:"Views"`
	CreatedAt int    `json:"CreatedAt"`
	UpdatedAt int    `json:"UpdatedAt"`
}
