// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePost struct {
	Slug     string `json:"Slug"`
	Title    string `json:"Title"`
	Content  string `json:"Content"`
	ImageURL string `json:"ImageUrl"`
}

type Post struct {
	Slug     string `json:"Slug"`
	Title    string `json:"Title"`
	UserID   int    `json:"UserID"`
	Content  string `json:"Content"`
	ImageURL string `json:"ImageURL"`
	Status   int    `json:"Status"`
	Views    int    `json:"Views"`
}
